apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keypad-flasher
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ required "host is required" .Values.host }}
    secretName: keypad-flasher-tls
  rules:
  - host: {{ required "host is required" .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keypad-flasher
            port:
              number: 80
